// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: userinfo.proto

#include "userinfo.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace userinfo {
PROTOBUF_CONSTEXPR ReqUserinfo::ReqUserinfo(
    ::_pbi::ConstantInitialized)
  : name_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , tokenstr_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , extr_message_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}){}
struct ReqUserinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReqUserinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReqUserinfoDefaultTypeInternal() {}
  union {
    ReqUserinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReqUserinfoDefaultTypeInternal _ReqUserinfo_default_instance_;
PROTOBUF_CONSTEXPR RespUserinfo::RespUserinfo(
    ::_pbi::ConstantInitialized)
  : message_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , extr_message_(&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{})
  , code_(0){}
struct RespUserinfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RespUserinfoDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~RespUserinfoDefaultTypeInternal() {}
  union {
    RespUserinfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RespUserinfoDefaultTypeInternal _RespUserinfo_default_instance_;
}  // namespace userinfo
static ::_pb::Metadata file_level_metadata_userinfo_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_userinfo_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_userinfo_2eproto = nullptr;

const uint32_t TableStruct_userinfo_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::userinfo::ReqUserinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::userinfo::ReqUserinfo, name_),
  PROTOBUF_FIELD_OFFSET(::userinfo::ReqUserinfo, tokenstr_),
  PROTOBUF_FIELD_OFFSET(::userinfo::ReqUserinfo, extr_message_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::userinfo::RespUserinfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::userinfo::RespUserinfo, code_),
  PROTOBUF_FIELD_OFFSET(::userinfo::RespUserinfo, message_),
  PROTOBUF_FIELD_OFFSET(::userinfo::RespUserinfo, extr_message_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::userinfo::ReqUserinfo)},
  { 9, -1, -1, sizeof(::userinfo::RespUserinfo)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::userinfo::_ReqUserinfo_default_instance_._instance,
  &::userinfo::_RespUserinfo_default_instance_._instance,
};

const char descriptor_table_protodef_userinfo_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\016userinfo.proto\022\010userinfo\"C\n\013ReqUserinf"
  "o\022\014\n\004name\030\001 \001(\t\022\020\n\010tokenstr\030\002 \001(\t\022\024\n\014ext"
  "r_message\030\003 \001(\t\"C\n\014RespUserinfo\022\014\n\004code\030"
  "\001 \001(\005\022\017\n\007message\030\002 \001(\t\022\024\n\014extr_message\030\003"
  " \001(\t2N\n\017UserInfoService\022;\n\010UserInfo\022\025.us"
  "erinfo.ReqUserinfo\032\026.userinfo.RespUserin"
  "fo\"\000b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_userinfo_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_userinfo_2eproto = {
    false, false, 252, descriptor_table_protodef_userinfo_2eproto,
    "userinfo.proto",
    &descriptor_table_userinfo_2eproto_once, nullptr, 0, 2,
    schemas, file_default_instances, TableStruct_userinfo_2eproto::offsets,
    file_level_metadata_userinfo_2eproto, file_level_enum_descriptors_userinfo_2eproto,
    file_level_service_descriptors_userinfo_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_userinfo_2eproto_getter() {
  return &descriptor_table_userinfo_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_userinfo_2eproto(&descriptor_table_userinfo_2eproto);
namespace userinfo {

// ===================================================================

class ReqUserinfo::_Internal {
 public:
};

ReqUserinfo::ReqUserinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:userinfo.ReqUserinfo)
}
ReqUserinfo::ReqUserinfo(const ReqUserinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    name_.Set(from._internal_name(), 
      GetArenaForAllocation());
  }
  tokenstr_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    tokenstr_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_tokenstr().empty()) {
    tokenstr_.Set(from._internal_tokenstr(), 
      GetArenaForAllocation());
  }
  extr_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    extr_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_extr_message().empty()) {
    extr_message_.Set(from._internal_extr_message(), 
      GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:userinfo.ReqUserinfo)
}

inline void ReqUserinfo::SharedCtor() {
name_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  name_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
tokenstr_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  tokenstr_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
extr_message_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  extr_message_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ReqUserinfo::~ReqUserinfo() {
  // @@protoc_insertion_point(destructor:userinfo.ReqUserinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ReqUserinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  name_.Destroy();
  tokenstr_.Destroy();
  extr_message_.Destroy();
}

void ReqUserinfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void ReqUserinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:userinfo.ReqUserinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmpty();
  tokenstr_.ClearToEmpty();
  extr_message_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ReqUserinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "userinfo.ReqUserinfo.name"));
        } else
          goto handle_unusual;
        continue;
      // string tokenstr = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_tokenstr();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "userinfo.ReqUserinfo.tokenstr"));
        } else
          goto handle_unusual;
        continue;
      // string extr_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_extr_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "userinfo.ReqUserinfo.extr_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ReqUserinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:userinfo.ReqUserinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "userinfo.ReqUserinfo.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string tokenstr = 2;
  if (!this->_internal_tokenstr().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_tokenstr().data(), static_cast<int>(this->_internal_tokenstr().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "userinfo.ReqUserinfo.tokenstr");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_tokenstr(), target);
  }

  // string extr_message = 3;
  if (!this->_internal_extr_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_extr_message().data(), static_cast<int>(this->_internal_extr_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "userinfo.ReqUserinfo.extr_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_extr_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:userinfo.ReqUserinfo)
  return target;
}

size_t ReqUserinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:userinfo.ReqUserinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string tokenstr = 2;
  if (!this->_internal_tokenstr().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_tokenstr());
  }

  // string extr_message = 3;
  if (!this->_internal_extr_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_extr_message());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ReqUserinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    ReqUserinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ReqUserinfo::GetClassData() const { return &_class_data_; }

void ReqUserinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<ReqUserinfo *>(to)->MergeFrom(
      static_cast<const ReqUserinfo &>(from));
}


void ReqUserinfo::MergeFrom(const ReqUserinfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:userinfo.ReqUserinfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _internal_set_name(from._internal_name());
  }
  if (!from._internal_tokenstr().empty()) {
    _internal_set_tokenstr(from._internal_tokenstr());
  }
  if (!from._internal_extr_message().empty()) {
    _internal_set_extr_message(from._internal_extr_message());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ReqUserinfo::CopyFrom(const ReqUserinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:userinfo.ReqUserinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ReqUserinfo::IsInitialized() const {
  return true;
}

void ReqUserinfo::InternalSwap(ReqUserinfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &name_, lhs_arena,
      &other->name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &tokenstr_, lhs_arena,
      &other->tokenstr_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &extr_message_, lhs_arena,
      &other->extr_message_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ReqUserinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_userinfo_2eproto_getter, &descriptor_table_userinfo_2eproto_once,
      file_level_metadata_userinfo_2eproto[0]);
}

// ===================================================================

class RespUserinfo::_Internal {
 public:
};

RespUserinfo::RespUserinfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:userinfo.RespUserinfo)
}
RespUserinfo::RespUserinfo(const RespUserinfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_message().empty()) {
    message_.Set(from._internal_message(), 
      GetArenaForAllocation());
  }
  extr_message_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    extr_message_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_extr_message().empty()) {
    extr_message_.Set(from._internal_extr_message(), 
      GetArenaForAllocation());
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:userinfo.RespUserinfo)
}

inline void RespUserinfo::SharedCtor() {
message_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  message_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
extr_message_.InitDefault();
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  extr_message_.Set("", GetArenaForAllocation());
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
code_ = 0;
}

RespUserinfo::~RespUserinfo() {
  // @@protoc_insertion_point(destructor:userinfo.RespUserinfo)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void RespUserinfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  message_.Destroy();
  extr_message_.Destroy();
}

void RespUserinfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void RespUserinfo::Clear() {
// @@protoc_insertion_point(message_clear_start:userinfo.RespUserinfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  message_.ClearToEmpty();
  extr_message_.ClearToEmpty();
  code_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* RespUserinfo::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 code = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          code_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string message = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "userinfo.RespUserinfo.message"));
        } else
          goto handle_unusual;
        continue;
      // string extr_message = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_extr_message();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "userinfo.RespUserinfo.extr_message"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* RespUserinfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:userinfo.RespUserinfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_code(), target);
  }

  // string message = 2;
  if (!this->_internal_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_message().data(), static_cast<int>(this->_internal_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "userinfo.RespUserinfo.message");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_message(), target);
  }

  // string extr_message = 3;
  if (!this->_internal_extr_message().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_extr_message().data(), static_cast<int>(this->_internal_extr_message().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "userinfo.RespUserinfo.extr_message");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_extr_message(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:userinfo.RespUserinfo)
  return target;
}

size_t RespUserinfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:userinfo.RespUserinfo)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string message = 2;
  if (!this->_internal_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_message());
  }

  // string extr_message = 3;
  if (!this->_internal_extr_message().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_extr_message());
  }

  // int32 code = 1;
  if (this->_internal_code() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_code());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData RespUserinfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    RespUserinfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*RespUserinfo::GetClassData() const { return &_class_data_; }

void RespUserinfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<RespUserinfo *>(to)->MergeFrom(
      static_cast<const RespUserinfo &>(from));
}


void RespUserinfo::MergeFrom(const RespUserinfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:userinfo.RespUserinfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_message().empty()) {
    _internal_set_message(from._internal_message());
  }
  if (!from._internal_extr_message().empty()) {
    _internal_set_extr_message(from._internal_extr_message());
  }
  if (from._internal_code() != 0) {
    _internal_set_code(from._internal_code());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void RespUserinfo::CopyFrom(const RespUserinfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:userinfo.RespUserinfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RespUserinfo::IsInitialized() const {
  return true;
}

void RespUserinfo::InternalSwap(RespUserinfo* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &message_, lhs_arena,
      &other->message_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &extr_message_, lhs_arena,
      &other->extr_message_, rhs_arena
  );
  swap(code_, other->code_);
}

::PROTOBUF_NAMESPACE_ID::Metadata RespUserinfo::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_userinfo_2eproto_getter, &descriptor_table_userinfo_2eproto_once,
      file_level_metadata_userinfo_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace userinfo
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::userinfo::ReqUserinfo*
Arena::CreateMaybeMessage< ::userinfo::ReqUserinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::userinfo::ReqUserinfo >(arena);
}
template<> PROTOBUF_NOINLINE ::userinfo::RespUserinfo*
Arena::CreateMaybeMessage< ::userinfo::RespUserinfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::userinfo::RespUserinfo >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
